before_script:
  - sudo apt-get update
  - sudo apt-get install chromium-browser
  - version=`curl -silent https://chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - file='chromedriver_linux64.zip'
  - wget https://chromedriver.storage.googleapis.com/${version}/${file}
  - export PATH=$PATH:$PWD
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

sudo: required

language: ruby
rvm:
  - 2.2.2

script:
  - bundle exec cucumber
