before_script:
  - sudo apt-get update
  - sudo apt-get install chromium-browser
  - wget https://npm.taobao.org/mirrors/chromedriver/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:$PWD
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

sudo: required

language: ruby
rvm:
  - 2.2.2

script:
  - bundle exec cucumber
